name: TaxonMarker_swarm
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - argtable2=2.13=hd590300_1004
  - arpack=3.9.1=nompi_h77f6705_101
  - biopython=1.84=py311h331c9d8_0
  - bottleneck=1.4.0=py311h9f3472d_2
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - clustalo=1.2.4=hdbdd923_8
  - contourpy=1.3.0=py311hd18a35c_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - expat=2.6.3=h5888daf_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonttools=4.53.1=py311h9ecbd09_1
  - freetype=2.12.1=h267a509_2
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py311hd18a35c_0
  - krb5=1.20.1=h81ceb04_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.42=h02bd663_0
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=24_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=24_linux64_openblas
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.3.3=h36d4200_3
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=24_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hb9d3cd8_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.2.13=h4ab18f5_6
  - matplotlib=3.9.2=py311h06a4308_0
  - matplotlib-base=3.9.2=py311h2b939e6_1
  - matplotlib-venn=1.1.1=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.5=he02047a_1
  - nomkl=1.0=h5ca1d4c_0
  - numexpr=2.10.0=py311h8d05612_100
  - numpy=1.26.4=py311h64a7726_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py311ha02d727_0
  - pcre2=10.42=hcad00b1_0
  - pillow=10.4.0=py311h5eee18b_0
  - pip=24.2=pyh8b19718_1
  - ply=3.11=pyhd8ed1ab_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyqt=5.15.10=py311h6a678d5_0
  - pyqt5-sip=12.13.0=py311h5eee18b_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.1=h2755cc3_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-igraph=0.11.5=py311h869fdc3_1
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=5_cp311
  - pytz=2024.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h8228510_1
  - requests=2.28.1=pyhd8ed1ab_1
  - scipy=1.14.1=py311he1f765f_0
  - setuptools=74.1.2=pyhd8ed1ab_0
  - sip=6.7.12=py311hb755f60_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.46.0=h6d4b2fc_0
  - swarm=3.1.4=h4ac6f70_0
  - texttable=1.7.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4.1=py311h9ecbd09_1
  - tzdata=2024a=h8827d51_1
  - urllib3=1.26.19=pyhd8ed1ab_0
  - vsearch=2.22.1=h6a68c12_2
  - wheel=0.44.0=pyhd8ed1ab_0
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
prefix: /home/gagoutin/.conda/envs/TaxonMarker_swarm
